services:
  excel:
    build: .
    image: excel:latest
    container_name: excel
    cpus: "0.5"
    mem_limit: 1g
    mem_reservation: 512m
    ports:
      - "9004:9004"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container:3306/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - TZ=Asia/Seoul
      - JAVA_TOOL_OPTIONS=-Duser.timezone=Asia/Seoul
      - SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_TIME_ZONE=Asia/Seoul
      - APP_EXPORT_STORAGE_PATH=/tmp/async-excel-export/files
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - excel-export-files:/tmp/async-excel-export/files
    networks:
      - blog-network
      - my-network
    restart: unless-stopped

volumes:
  excel-export-files:

networks:
  blog-network:
    external: true
  my-network:
    external: true
